### ISSUE TITLE
Webhook cooldown is applied even if webhook is not sent.

### ISSUE THREAD

**Issue by TheDeafCreeper** [ShortyDev/PolarLogs#1]
The cooldown for webhooks is checked and applied before all other checks, so if something else prevents the webhook (such as a lv requirement) from being sent the webhook will still be put on cooldown, causing alerts to not be sent if they all happen within the cooldown time (5 seconds by default).

**Comment by ShortyDev** [comment]
Thank you for reporting this issue. I fixed this in the latest version, 2.3 commit 04f1c7174013a8f5e5c873a5bac9d4f3d50df410. Please let me know if you notice any other issues.

Release: https://github.com/ShortyDev/PolarLogs/releases/tag/2.3
