### ISSUE TITLE
Punishment Logs do not respect cooldown.

### ISSUE THREAD

**Issue by TheDeafCreeper** [ShortyDev/PolarLogs#2]
When the punishment logs are sent, they are usually spammed.
![image](https://github.com/user-attachments/assets/cf413954-afff-454d-b185-93d52c111f3f)

**Comment by ShortyDev** [comment]
Thank you, this issue is now fixed in version 2.4 - changes https://github.com/ShortyDev/PolarLogs/commit/1ef080733eec2f3f5251e65f7f05b85b691e04ec

Release: https://github.com/ShortyDev/PolarLogs/releases/tag/2.4
