### ISSUE TITLE
Punishments are sometimes logged without a punishment actually being executed.

### ISSUE THREAD

**Issue by TheDeafCreeper** [ShortyDev/PolarLogs#3]
Sometimes Polar Logs will log a punishment, however that punishment is not reflected by the moderation plugin.
![image](https://github.com/user-attachments/assets/e6b43f90-3b40-40d4-a00f-47c4e69c7dba)

**Comment by ShortyDev** [comment]
This is something that is out of my control, but I think this might be fixed if the cooldown is applied. I'll try to do that.
